# Generated by Django 3.0.2 on 2020-06-09 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pub_date',
            new_name='exp_date',
        ),
    ]
